# Generated by Django 3.2 on 2023-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230512_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=254, unique=True, verbose_name='Пароль'),
        ),
    ]
